### PR TITLE
parser: Prevent duplicate tokens from happening and related tasks

### LINKED ISSUE #75: SIMPLE_IDENTIFIER  is not assigned in exception
Hi
Ex:
```
def a():
    env = None
    try:
        something()
    except Exception as e:
        print("Something wrong")
        raise e from None
```
and `e` is not SIMPLE_IDENTIFIER.
Vis:
selection_007

### PR DESCRIPTION
**Pull request by abeaumont**
* Annotates new node type
* Update the testsuite

Depends on https://github.com/bblfsh/sdk/pull/164
Fixes #75

### CODE REVIEW

File: driver/normalizer/parser.go [hunk 1]
```diff
@@ -63,17 +63,18 @@ var ToNoder = &native.ObjectToNoder{
 		"Compare":  {"comparators": true, "ops": true},
 		// FIXME: check call.keywords
 		//"Call"                    : { "args": true, "keywords": true},
-		"With":                    {"body": true, "items": true},
-		"FunctionDef":             {"body": true, "decorator_list": true},
-		"Lambda":                  {"body": true},
-		"arguments":               {"defaults": true},
-		"Try":                     {"body": true, "orelse": true, "finalbody": true, "handlers": true},
```
Comment (manucorporat) [inline driver/normalizer/parser.go]: LGTM!

I am not very familiarized with the API to annotate nodes, out of curiosity, how is removing `handlers: true` affecting?

Comment (abeaumont) [inline driver/normalizer/parser.go]: It means that `Try.handlers` are not promoted to node. https://github.com/bblfsh/python-driver/pull/80/files#diff-56de3fb994af9b7ff9f631ea2d5aec42 shows how the uast changes in this case.

**Comment by abeaumont** [comment]
Rebased for conflict resolution
