### PR TITLE
Comment and other fixes

### LINKED ISSUE #167: Driver returns twice every inline comment
When an inline comment is parsed, it is returned a structure that is different compared to other comments or compared to other drivers:
It is returned a `<SameLineNoopscontaining roleComment>` having `position` and containing a `<NoopSameLine roleComment>` without `position`.

The comment token itself contains a leading `#` character what does not happen for regular python comments.
```python
a = Animal() # line comentary
```

image

***addendum:***
This issue might be related to these similar ones in other languages drivers:
https://github.com/bblfsh/javascript-driver/issues/36 https://github.com/bblfsh/go-driver/issues/28 https://github.com/bblfsh/java-driver/issues/86

### PR DESCRIPTION
**Pull request by juanjux**
- Upgrade to SDK 2.13.x
- Adds Bool semantic object.
- Fixes comments being eated when they were part of some node that would be promoted to a semantic object.
- Remove the removal of the `#` in the native driver and moved it to the Go part to harmonize what other drivers to.
- Adds several new tests related to the headaches I had with this.

Needs bblfsh/sdk/pull/354 to be merged before because of the comment parsing fixes (so CI will fail until then).

Fixes #167.

### CODE REVIEW

File: driver/normalizer/annotation.go [hunk 1]
```diff
@@ -88,6 +89,21 @@ func loopAnnotate(typ string, mainRole role.Role, roles ...role.Role) Mapping {
 	}), roles...)
 }
 
+func uncomment_bash(s string) (string, error) {
+	if strings.HasPrefix(s, "#") {
```
Comment (creachadair) [inline driver/normalizer/annotation.go]: `return strings.TrimPrefix(s, "#"), nil`

File: driver/normalizer/annotation.go [hunk 2]
```diff
@@ -356,20 +372,17 @@ var Annotations = []Mapping{
...
 
-	AnnotateType("NoopLine", FieldRoles{
-		"noop_line": {Rename: uast.KeyToken},
-	}, role.Noop, role.Comment),
-
-	AnnotateType("NoopSameLine", FieldRoles{
-		"s": {Rename: uast.KeyToken},
-	}, role.Noop, role.Comment),
+	AnnotateType("NoopLine", MapObj(Obj{
+		"noop_line": UncommentBashLike("txt"),
```
Comment (dennwc) [inline driver/normalizer/annotation.go]: But Annotated should not change values. All other drivers leave it with `#`, and this was asked by ML - preserve all node tokens in the `@token`, so it can match the positional info.

File: driver/normalizer/annotation.go [hunk 3]
```diff
@@ -88,6 +89,21 @@ func loopAnnotate(typ string, mainRole role.Role, roles ...role.Role) Mapping {
...
+	}
+	return s, nil
+}
+
+func comment_bash(s string) (string, error) {
+	return "#" + s, nil
+}
+
+func UncommentBashLike(vr string) Op {
+	return StringConv(Var(vr), uncomment_bash, comment_bash)
```
Comment (creachadair) [inline driver/normalizer/annotation.go]: Is this the correct order? Does it uncomment then re-comment?

File: driver/normalizer/normalizer.go [hunk 4]
```diff
@@ -72,81 +72,110 @@ func identifierWithPos(nameVar string) ObjectOp {
...
-	return AnnotateType(typ, MapObj(
-		Fields{
-			{Name: tokenKey, Op: Var("name")},
-		},
-		Fields{
-			{Name: tokenKey,
-			 Op: UASTType(uast.Identifier{}, Obj{
-			 	"Name": Var("name"),
-			 })},
+func mapStr(nativeType string) Mapping {
```
Comment (creachadair) [inline driver/normalizer/normalizer.go]: This name is telegraphic enough that I think this function deserves a brief comment.

File: driver/fixtures/fixtures_test.go [hunk 5]
```diff
@@ -35,11 +36,11 @@ var Suite = &fixtures.Suite{
...
 			"Str",
 			"StringLiteral",
+			"alias",
 			"arg",
 			"kwarg",
 			"kwonly_arg",
 			"vararg",
-			"alias",
 		},
 	},
```
Comment (dennwc) [inline driver/fixtures/fixtures_test.go]: If you like, you can also try to enable the token verification. Here is an example for [C#](https://github.com/bblfsh/csharp-driver/blob/master/driver/fixtures/fixtures_test.go#L46). Although Python's tokenizer may fail it. But maybe at least for some nodes it doesn't?

File: driver/normalizer/annotation.go (hunk 1 above)
Comment (creachadair) [reply driver/normalizer/annotation.go]: Separately: Please use `mixedCase` not `snake_case`. https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps

File: driver/normalizer/normalizer.go (hunk 4 above)
Comment (dennwc) [reply driver/normalizer/normalizer.go]: Sorry, Go convention: `// mapStr ...`

File: driver/normalizer/normalizer.go [hunk 6]
```diff
@@ -72,81 +72,111 @@ func identifierWithPos(nameVar string) ObjectOp {
...
 
-	MapSemantic("StringLiteral", uast.String{}, MapObj(
-		Obj{
-			"s": Var("val"),
-		},
+	MapSemantic("NoopSameLine", uast.Comment{}, MapObj(
 		Obj{
-			"Value":  Var("val"),
-			"Format": String(""),
+			"s": CommentText([2]string{"#", ""}, "comm"),
```
Comment (dennwc) [inline driver/normalizer/normalizer.go]: No trim here? Just wondering.

File: driver/normalizer/normalizer.go (hunk 4 above)
Comment (creachadair) [reply driver/normalizer/normalizer.go]: It's okay to relax that for unexported names (though it certainly helps if they later get exported).

File: driver/normalizer/normalizer.go (hunk 6 above)
Comment (juanjux) [reply driver/normalizer/normalizer.go]: No, the text of these are always right.
